auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  gcr.io/k8s-staging-nfd/node-feature-discovery: davidliyutong/node-feature-discovery
  k8s.gcr.io/kube-proxy: davidliyutong/kube-proxy
  k8s.gcr.io/pause: davidliyutong/pause
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: davidliyutong/nfs-subdir-external-provisioner
  ghcr.io/suwayomi/tachidesk: davidliyutong/tachidesk
