auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  k8s.gcr.io/kube-apiserver: davidliyutong/kube-apiserver
  k8s.gcr.io/kube-controller-manager: davidliyutong/kube-controller-manager
  k8s.gcr.io/kube-scheduler: davidliyutong/kube-scheduler
  k8s.gcr.io/kube-proxy: davidliyutong/kube-proxy
  k8s.gcr.io/pause: davidliyutong/pause
  k8s.gcr.io/etcd: davidliyutong/etcd
  k8s.gcr.io/coredns/coredns: davidliyutong/coredns
  k8s.gcr.io/liveness: davidliyutong/liveness
  k8s.gcr.io/defaultbackend: davidliyutong/defaultbackend
  k8s.gcr.io/metrics-server/metrics-server: davidliyutong/metrics-server
  gcr.io/kubebuilder/kube-rbac-proxy: davidliyutong/kube-rbac-proxy
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: davidliyutong/nfs-subdir-external-provisioner
  gcr.io/k8s-minikube/kicbase: davidliyutong/kicbase
  gcr.io/k8s-minikube/storage-provisioner: davidliyutong/storage-provisioner
  k8s.gcr.io/ingress-nginx/controller: davidliyutong/ingress-nginx-controller
  k8s.gcr.io/ingress-nginx/kube-webhook-certgen: davidliyutong/ingress-nginx-kube-webhook-certgen
  k8s.gcr.io/defaultbackend-amd64: davidliyutong/ingress-nginx-defaultbackend-amd64
  ghcr.io/suwayomi/tachidesk: davidliyutong/tachidesk
